# Generated by Django 3.0 on 2020-03-10 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(default=None, verbose_name='Описание')),
                ('address', models.TextField(db_index=True, default=None, verbose_name='Адрес')),
                ('date_add', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('unp', models.BigIntegerField(verbose_name='УНП')),
            ],
            options={
                'verbose_name': 'Агент',
                'verbose_name_plural': 'Агенты',
            },
        ),
        migrations.CreateModel(
            name='Vagon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=255, verbose_name='Номер')),
                ('nakladnaya', models.CharField(db_index=True, default=0, max_length=255, verbose_name='Накладная')),
                ('date_add', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('last_in', models.DateTimeField(db_index=True, null=True, verbose_name='время последнего въезда')),
                ('last_out', models.DateTimeField(db_index=True, null=True, verbose_name='время последнего выезда')),
                ('ves_in', models.FloatField(db_index=True, null=True, verbose_name='вес на въезде')),
                ('ves_out', models.FloatField(db_index=True, null=True, verbose_name='вес на выезде')),
                ('netto', models.FloatField(db_index=True, null=True, verbose_name='полсденее нетто')),
                ('status_in', models.BooleanField(default=False, verbose_name='На территории?')),
                ('agent', models.ManyToManyField(to='ves.Agent')),
            ],
            options={
                'verbose_name': 'Вагон',
                'verbose_name_plural': 'Вагоны',
            },
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=255, verbose_name='Номер')),
                ('number_pricep', models.CharField(db_index=True, max_length=255, verbose_name='номер прицепа')),
                ('date_add', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('last_in', models.DateTimeField(db_index=True, null=True, verbose_name='время последнего въезда')),
                ('last_out', models.DateTimeField(db_index=True, null=True, verbose_name='время последнего выезда')),
                ('ves_in', models.FloatField(null=True, verbose_name='вес на въезде')),
                ('ves_out', models.FloatField(null=True, verbose_name='вес на выезде')),
                ('nakladnaya', models.CharField(db_index=True, default=0, max_length=255, verbose_name='Накладная')),
                ('netto', models.FloatField(null=True, verbose_name='полсденее нетто')),
                ('status_in', models.BooleanField(default=False, verbose_name='На территории?')),
                ('agent', models.ManyToManyField(to='ves.Agent')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='ActionUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=255, verbose_name='действие')),
                ('where', models.CharField(db_index=True, max_length=255, verbose_name='где')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('parentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
            },
        ),
    ]
