# Generated by Django 3.0 on 2020-04-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Auto', models.BooleanField(default=False, verbose_name='Авто занято')),
                ('Zd', models.BooleanField(default=False, verbose_name='ЖД занято')),
            ],
        ),
    ]
