# Generated by Django 3.0 on 2020-05-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ves', '0003_auto_20200420_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='driver',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Водитель'),
        ),
        migrations.CreateModel(
            name='CatalogTrailer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tara', models.FloatField(db_index=True, null=True, verbose_name='вес')),
                ('number', models.CharField(db_index=True, max_length=255, verbose_name='Номер')),
                ('marka', models.CharField(db_index=True, max_length=255, verbose_name='Марка')),
                ('model', models.CharField(db_index=True, max_length=255, verbose_name='Модель')),
                ('date_add', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ves.Agent')),
            ],
            options={
                'verbose_name': 'Прицеп',
                'verbose_name_plural': 'Прицепы',
            },
        ),
        migrations.CreateModel(
            name='CatalogAuto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tara', models.FloatField(db_index=True, null=True, verbose_name='вес')),
                ('number', models.CharField(db_index=True, max_length=255, verbose_name='Номер')),
                ('marka', models.CharField(db_index=True, max_length=255, verbose_name='Марка')),
                ('model', models.CharField(db_index=True, max_length=255, verbose_name='Модель')),
                ('date_add', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ves.Agent')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.AddField(
            model_name='auto',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ves.CatalogAuto'),
        ),
    ]
