# Generated by Django 3.0 on 2020-03-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ves', '0003_datanakladnayaauto'),
    ]

    operations = [
        migrations.AddField(
            model_name='datanakladnayaauto',
            name='number',
            field=models.BigIntegerField(null=True, verbose_name='номер в накладной'),
        ),
    ]
