# Generated by Django 3.0 on 2020-03-17 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ves', '0004_datanakladnayaauto_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='agent',
        ),
    ]
