# Generated by Django 3.0 on 2020-03-17 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ves', '0005_remove_auto_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vagon',
            name='agent',
        ),
        migrations.AddField(
            model_name='auto',
            name='agents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ves.Agent'),
        ),
        migrations.AddField(
            model_name='vagon',
            name='agent_vagon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ves.Agent'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Наименование'),
        ),
    ]
