# Generated by Django 3.0 on 2020-05-11 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ves', '0005_auto_20200511_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='название')),
            ],
        ),
        migrations.AddField(
            model_name='datanakladnayaauto',
            name='name_drive',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='имя водителя'),
        ),
        migrations.AddField(
            model_name='datanakladnayaauto',
            name='osnovanie',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='основание'),
        ),
        migrations.AddField(
            model_name='datanakladnayaauto',
            name='pogruzka',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='место погрузки'),
        ),
        migrations.AddField(
            model_name='datanakladnayaauto',
            name='prinyal',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='кто принял'),
        ),
        migrations.AddField(
            model_name='datanakladnayaauto',
            name='putlist',
            field=models.BigIntegerField(db_index=True, null=True, verbose_name='номер путевого листа'),
        ),
        migrations.AddField(
            model_name='datanakladnayaauto',
            name='razreshil',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='кто разрешил'),
        ),
        migrations.AddField(
            model_name='datanakladnayaauto',
            name='productionId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ves.Production'),
        ),
        migrations.AddField(
            model_name='datanakladnayavagon',
            name='productionId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ves.Production'),
        ),
    ]
