# Generated by Django 3.0 on 2020-05-12 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ves', '0006_auto_20200511_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='auto_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ves.Auto'),
        ),
    ]
