# Generated by Django 3.0 on 2020-05-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ves', '0007_production_auto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='datanakladnayaauto',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
