# Generated by Django 3.0 on 2020-05-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ves', '0008_datanakladnayaauto_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datanakladnayaauto',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
