# Generated by Django 3.0 on 2020-05-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ves', '0009_auto_20200512_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='tara',
            field=models.IntegerField(null=True, verbose_name='Порожний'),
        ),
    ]
