# Generated by Django 3.0 on 2020-05-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ves', '0012_auto_20200513_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogauto',
            name='number',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Номер'),
        ),
    ]
