# Generated by Django 3.0 on 2020-05-13 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ves', '0013_auto_20200513_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='catalogPricep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ves.CatalogTrailer'),
        ),
    ]
