# Generated by Django 3.0 on 2020-05-13 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ves', '0014_auto_catalogpricep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='agents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ves.Agent'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ves.CatalogAuto'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='catalogPricep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ves.CatalogTrailer'),
        ),
    ]
