# Generated by Django 3.0 on 2020-05-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ves', '0015_auto_20200513_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='number',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='номер'),
        ),
    ]
